# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    description: "A simple command that prints circle_ci_Id"
    steps:
      - run: "echo version number $CIRCLE_WORKFLOW_ID"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  save-hello-world-output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Save Hello World"
          command: echo Hello world > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - output.txt

  print-saved-file:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Print Hello World"
          command: cat output.txt

  print-my-name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "my name"
          command: "echo hello $MY_NAME"

  run_command:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - save-hello-world-output
      - print-my-name
      - print-saved-file:
          requires:
            - save-hello-world-output
      - run_command
